steps:
  - name: 'python:3.9'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install -r requirements.txt

  - name: 'python:3.9'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Running integration Tests..."
        python -m integration .

  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cp utils.py ./cloudfunctions/handle_messages/
        cp utils.py ./cloudfunctions/main_logic/
        cp utils.py ./cloudfunctions/pubsub/

timeout: '600s'
